modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/EdwinMindcraft/origins-architectury/issues"

[[mods]]
modId="origins"
version="${version}"
displayName="Origins"
logoFile= "origins_icon.png"
authors="Apace"
description='''
This mod adds several origins with passive abilities to the game, which you can choose from at the beginning of the game.
'''

[[dependencies.origins]]
    modId="forge"
    mandatory=true
    versionRange="${forge_requirements}"
    ordering="NONE"
    side="BOTH"

[[dependencies.origins]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.origins]]
    modId="calio"
    mandatory=true
    versionRange="[1.20.1-1.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.origins]]
    modId="apoli"
    mandatory=true
    versionRange="[1.20.1-2.9,)"
    ordering="NONE"
    side="BOTH"